server:
  port: 8080
  address: localhost

spring:
  profiles:
    active: default
  liquibase:
    clear-checksums: off
    change-log: classpath:/db/changelog/changelog.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/application_user
    username: postgres
    password: postgres
