server:
  port: 8080
  address: localhost
spring:
  profiles:
    active: default
# liquibase
  liquibase:
    change-log: classpath:/db/changelog/changelog.yaml
    enabled: true
# blocking datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/application_user
    username: postgres
    password: postgres
# non-blocking datasource
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/application_user
    password: postgres
    username: postgres
    template:
      host: localhost
      port: 5432
      database: application_user


